FROM gradle:7.6.1 AS builder
WORKDIR /backend
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar

FROM openjdk:17-jdk
COPY --from=builder /backend/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=dev","-jar","app.jar"]